### ISSUE TITLE
demo运行就直接崩溃

### ISSUE THREAD

**Issue by yangzai100** [LianjiaTech/keframe#24]
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
I/flutter ( 6453): ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞══════════════════════
I/flutter ( 6453): [exception: Null check operator used on a null value]
I/flutter ( 6453): [library: Flutter framework]
I/flutter ( 6453): [stack: #0      RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:727:26)
I/flutter ( 6453): #1      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
I/flutter ( 6453): #2      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
I/flutter ( 6453): #3      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
I/flutter ( 6453): #4      RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3618:31)
I/flutter ( 6453): #5      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
I/flutter ( 6453): #6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
I/flutter ( 6453): #7      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
I/flutter ( 6453): #8      RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:183:19)
I/flutter ( 6453): #9      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
I/flutter ( 6453): #10     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:183:19)
I/flutter ( 6453): #11     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
I/flutter ( 6453): #12     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:183:19)
I/flutter ( 6453): #13     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
I/flutter ( 6453): #14     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
I/flutter ( 6453): #15     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
I/flutter ( 6453): #16     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
I/flutter ( 6453): #17     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
I/flutter ( 6453): #18     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
I/flutter ( 6453): #19     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
I/flutter ( 6453): #20     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
I/flutter ( 6453): #21     RenderSliverHelpers.hitTestBoxChild.<anonymous closure> (package:flutter/src/rendering/sliver.dart:1669:22)
I/flutter ( 6453): #22     BoxHitTestResult.addWithOutOfBandPosition (package:flutter/src/rendering/box.dart:902:31)
I/flutter ( 6453): #23     RenderSliverHelpers.hitTestBoxChild (package:flutter/src/rendering/sliver.dart:1666:19)
I/flutter ( 6453): #24     RenderSliverMultiBoxAdaptor.hitTestChildren (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:564:11)
I/flutter ( 6453): #25     RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1287:11)
I/flutter ( 6453): #26     SliverHitTestResult.addWithAxisOffset (package:flutter/src/rendering/sliver.dart:858:31)

**Comment by yangzai100** [comment]
Flutter 版本是3.3
